# Generated by Django 3.1.7 on 2021-09-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название юрлица')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('business_address', models.CharField(max_length=250, verbose_name='Юр. адрес')),
                ('warehouse_address', models.CharField(max_length=250, verbose_name='Адрес склада')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('logo_path', models.CharField(max_length=250, verbose_name='Путь к логотипу')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'db_table': 'client_employees',
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Функции',
                'verbose_name_plural': 'Функции',
                'db_table': 'functions',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=6, verbose_name='Индекс')),
                ('city', models.CharField(max_length=45, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
                ('entrance', models.IntegerField(null=True, verbose_name='Подъезд')),
                ('flat', models.CharField(max_length=10, verbose_name='Квартира')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата завершения')),
                ('active', models.BooleanField(verbose_name='Объект сдан')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.client', verbose_name='Клиент')),
            ],
            options={
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=45, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=45, verbose_name='Телефон')),
                ('position', models.CharField(max_length=60, verbose_name='Должность')),
                ('photo_path', models.CharField(max_length=250, verbose_name='Путь к фото')),
                ('active', models.BooleanField(verbose_name='Работает')),
                ('auth_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('photo_path', models.CharField(max_length=250, null=True, verbose_name='Путь к фото')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'user_documents',
            },
        ),
        migrations.CreateModel(
            name='UserContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('photo_path', models.CharField(max_length=250, null=True, verbose_name='Путь к фото')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'user_contracts',
            },
        ),
        migrations.CreateModel(
            name='TimeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время конца')),
                ('position', models.CharField(max_length=45, verbose_name='Должность')),
                ('comment', models.TextField(max_length=1200, verbose_name='Комментарий')),
                ('objects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.objects', verbose_name='Объект')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'time_report',
            },
        ),
        migrations.CreateModel(
            name='ObjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.objects', verbose_name='Объект')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'object_user',
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=250, verbose_name='Путь к фото')),
                ('objects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.objects', verbose_name='Объект')),
            ],
            options={
                'db_table': 'object_photo',
            },
        ),
        migrations.CreateModel(
            name='ObjectComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('object_comments_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.objectcomments', verbose_name='Родительский комментарий')),
                ('objects_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.objects', verbose_name='Объект')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'object_comments',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1200, verbose_name='Текст новости')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Автор')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='GroupFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.functions', verbose_name='Функция')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Доступные группам функции',
                'verbose_name_plural': 'Доступные группам функции',
                'db_table': 'group_functions',
            },
        ),
    ]
