# Generated by Django 3.1.7 on 2021-09-21 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210920_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcomments',
            name='object_comments_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.objectcomments', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='entrance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='flat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='usercontracts',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь к фото'),
        ),
    ]
