# Generated by Django 3.1.7 on 2021-09-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_userprofile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectuser',
            options={'verbose_name': 'Рабочие на объектах', 'verbose_name_plural': 'Рабочие на объектах'},
        ),
    ]
