# Generated by Django 3.1.7 on 2021-10-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210924_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemployees',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='timereport',
            options={'verbose_name': 'Часовой отчет', 'verbose_name_plural': 'Часовые отчеты'},
        ),
        migrations.AddField(
            model_name='client',
            name='account_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email для счетов'),
        ),
        migrations.AddField(
            model_name='client',
            name='account_operator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Оператор электронных счетов'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Номер счета в банке'),
        ),
        migrations.AddField(
            model_name='client',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='client',
            name='electronic_number',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Номер электронных счетов'),
        ),
        migrations.AddField(
            model_name='client',
            name='index_operator',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Индекс посредника'),
        ),
        migrations.AddField(
            model_name='client',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat',
            field=models.IntegerField(blank=True, null=True, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='clientemployees',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.client', verbose_name='Фирма'),
        ),
        migrations.AddField(
            model_name='clientemployees',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AddField(
            model_name='clientemployees',
            name='work_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рабочий Email'),
        ),
        migrations.AddField(
            model_name='clientemployees',
            name='work_phone',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Рабочий телефон'),
        ),
        migrations.AddField(
            model_name='functions',
            name='text',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='groupfunctions',
            name='edit',
            field=models.BooleanField(blank=True, null=True, verbose_name='Редактирование'),
        ),
        migrations.AddField(
            model_name='groupfunctions',
            name='read',
            field=models.BooleanField(blank=True, null=True, verbose_name='Чтение'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='objects',
            name='accident_insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страховка от несчастных случаев'),
        ),
        migrations.AddField(
            model_name='objects',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.clientemployees', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='objects',
            name='habitation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='objects',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страховка здоровья'),
        ),
        migrations.AddField(
            model_name='objects',
            name='work_description',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание работ'),
        ),
        migrations.AddField(
            model_name='objectuser',
            name='comment',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='objectuser',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец работ'),
        ),
        migrations.AddField(
            model_name='objectuser',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало работ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_fin',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес в Финляндии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_own',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес в своей стране'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto',
            field=models.BooleanField(default=False, verbose_name='Свой автомобиль'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Счет в банке'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ботинки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='english',
            field=models.BooleanField(default=False, verbose_name='Английский язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estonian',
            field=models.BooleanField(default=False, verbose_name='Эстонский язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='finnish',
            field=models.BooleanField(default=False, verbose_name='Финский язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jacket',
            field=models.IntegerField(blank=True, null=True, verbose_name='Куртка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Другой язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pants',
            field=models.IntegerField(blank=True, null=True, verbose_name='Штаны'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_fin',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Телефон в Финляндии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='russian',
            field=models.BooleanField(default=False, verbose_name='Русский язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Футболка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Что умеет делать'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_code_fin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Финский номер социального страхования'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_code_own',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер социального страхования'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Налоговый номер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tool',
            field=models.BooleanField(default=False, verbose_name='Свой инструмент'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_address',
            field=models.JSONField(verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='warehouse_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='functions',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Объект сдан'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='date_end',
            field=models.DateField(verbose_name='Конец работ'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='date_start',
            field=models.DateField(verbose_name='Начало работ'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='index',
            field=models.CharField(max_length=12, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(max_length=60, verbose_name='Специальность'),
        ),
    ]
