# Generated by Django 3.1.7 on 2021-10-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20211017_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functions',
            name='text',
            field=models.CharField(max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clientemployees', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='objectuser',
            name='start_date',
            field=models.DateField(verbose_name='Начало работ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(max_length=45, verbose_name='Гражданство'),
        ),
    ]
