# Generated by Django 3.1.7 on 2021-11-19 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0013_auto_20211113_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_save', models.DateTimeField(verbose_name='Последнее сохранение')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет')),
                ('text', models.TextField(max_length=1000, verbose_name='Содержимое')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блокнот',
                'verbose_name_plural': 'Блокноты',
                'db_table': 'notes',
            },
        ),
    ]
