# Generated by Django 3.1.7 on 2021-11-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет блокнота'),
        ),
    ]
