# Generated by Django 3.1.7 on 2021-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_auto_20211119_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfunctions',
            name='edit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Редактирование'),
        ),
        migrations.AlterField(
            model_name='groupfunctions',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Чтение'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='last_save',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее сохранение'),
        ),
    ]
