# Generated by Django 3.1.7 on 2021-12-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20211124_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности для клиентов',
                'db_table': 'position_client',
            },
        ),
        migrations.CreateModel(
            name='PositionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности для профилей',
                'db_table': 'position_profile',
            },
        ),
        migrations.AlterField(
            model_name='clientemployees',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.positionclient', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.positionprofile', verbose_name='Специальность'),
        ),
    ]
