# Generated by Django 3.1.7 on 2021-12-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_auto_20211208_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория чеков',
                'verbose_name_plural': 'Категории чеков',
                'db_table': 'cheque_category',
            },
        ),
        migrations.CreateModel(
            name='DocumentsMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'documents_mode',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Стоимость без налога')),
                ('tax', models.IntegerField(blank=True, null=True, verbose_name='НДС')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка (%)')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('measurement', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Товар/услуга',
                'verbose_name_plural': 'Товары/услуги',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(verbose_name='Налог в %')),
            ],
            options={
                'verbose_name': 'НДС',
                'verbose_name_plural': 'НДС',
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name='Срок в днях')),
            ],
            options={
                'verbose_name': 'Срок',
                'verbose_name_plural': 'Сроки',
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='WaybillGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цель поездки',
                'verbose_name_plural': 'Цели поездок',
                'db_table': 'waybill_goal',
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата поездки')),
                ('departure', models.CharField(max_length=250, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=250, verbose_name='Пункт назначенния')),
                ('kilometrage', models.IntegerField(verbose_name='Километраж')),
                ('time_start', models.TimeField(verbose_name='Время начала поездки')),
                ('time_end', models.TimeField(verbose_name='Время конца поездки')),
                ('auto_mark', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('auto_type', models.CharField(max_length=60, verbose_name='Тип коробки')),
                ('auto_fuel', models.CharField(max_length=60, verbose_name='Тип топлива')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.waybillgoal', verbose_name='Цель поездки')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'db_table': 'waybill',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='Дата покупки')),
                ('object_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Номер объекта')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Заметки')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Пояснение к счету')),
                ('number_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ссылки')),
                ('items', models.ManyToManyField(to='server.Items', verbose_name='Товары/услуги')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.objects', verbose_name='Объект')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.term', verbose_name='Срок оплаты')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Способ оплаты')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета')),
                ('date_receipt', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('date', models.DateField(verbose_name='Дата покупки')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место покупки')),
                ('price', models.FloatField(verbose_name='Сумма покупки')),
                ('bundle', models.CharField(blank=True, max_length=100, null=True, verbose_name='от 2х чеков')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Заметки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.chequecategory', verbose_name='Категория')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.tax', verbose_name='НДС')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.userprofile', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.client', verbose_name='Клиент')),
                ('items', models.ManyToManyField(to='server.Items', verbose_name='Товары/услуги')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.term', verbose_name='Срок предложения')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='DocumentsClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.client', verbose_name='Клиент')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.documentsmode', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ с клиентом',
                'verbose_name_plural': 'Документы с клиентами',
                'db_table': 'documents_client',
            },
        ),
        migrations.CreateModel(
            name='DocumentsAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.documentsmode', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Бухгалтерский документ',
                'verbose_name_plural': 'Бухгалтерские документы',
                'db_table': 'documents_accounting',
            },
        ),
        migrations.CreateModel(
            name='ChequeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250, verbose_name='Путь к файлу')),
                ('purchases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.purchases', verbose_name='Покупка')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.sales', verbose_name='Покупка')),
            ],
            options={
                'verbose_name': 'Фото чеков',
                'verbose_name_plural': 'Фото чеков',
                'db_table': 'cheque_documents',
            },
        ),
    ]
