# Generated by Django 3.1.7 on 2021-12-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_chequecategory_chequedocuments_documentsaccounting_documentsclient_documentsmode_items_offer_purchas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedocuments',
            name='purchases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='server.purchases', verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='chequedocuments',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='server.sales', verbose_name='Покупка'),
        ),
    ]
