# Generated by Django 3.1.7 on 2022-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20220113_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(to='server.Items', verbose_name='Товары/услуги'),
        ),
    ]
