# Generated by Django 3.1.7 on 2022-01-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20220113_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='items',
            field=models.ManyToManyField(blank=True, to='server.Items', verbose_name='Товары/услуги'),
        ),
    ]
