# Generated by Django 3.1.7 on 2022-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20220114_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
