# Generated by Django 3.1.7 on 2022-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_offer_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='kilometrage',
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(default='Выставлен', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата конца поездки'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала поездки'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='kilometrage_end',
            field=models.IntegerField(null=True, verbose_name='Километраж в конце поездки'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='kilometrage_start',
            field=models.IntegerField(null=True, verbose_name='Километраж в начале поездки'),
        ),
    ]
