# Generated by Django 3.1.7 on 2022-02-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_auto_20220128_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='server.userprofile', verbose_name='Автор'),
        ),
    ]
