# Generated by Django 3.1.7 on 2022-02-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_calendar_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=10, verbose_name='Тема')),
                ('language', models.CharField(default='ru', max_length=2, verbose_name='Язык')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Настройки польщователя',
                'verbose_name_plural': 'Настройки пользователя',
                'db_table': 'user_settings',
            },
        ),
    ]
