# Generated by Django 3.1.7 on 2022-02-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectcomments',
            options={'verbose_name': 'Комментарий к объекту', 'verbose_name_plural': 'Комментарии к объектам'},
        ),
        migrations.CreateModel(
            name='ContactComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clientemployees', verbose_name='Клиент')),
                ('contact_comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.contactcomments', verbose_name='Родительский комментарий')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к контакту',
                'verbose_name_plural': 'Комментарии к контактам',
                'db_table': 'contact_comments',
            },
        ),
        migrations.CreateModel(
            name='ClientComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.client', verbose_name='Клиент')),
                ('client_comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.clientcomments', verbose_name='Родительский комментарий')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к клиенту',
                'verbose_name_plural': 'Комментарии к клиентам',
                'db_table': 'client_comments',
            },
        ),
    ]
