# Generated by Django 3.1.7 on 2022-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_objects_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='percent_delay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент по просрочке'),
        ),
        migrations.AddField(
            model_name='sales',
            name='printed',
            field=models.BooleanField(default=False, verbose_name='Повторный счет'),
        ),
        migrations.AddField(
            model_name='sales',
            name='remainder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Напоминание'),
        ),
    ]
