# Generated by Django 3.1.7 on 2022-03-09 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0032_auto_20220309_1855'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE sales_id_seq RESTART WITH 10000;'
        ),
        migrations.RunSQL(
            'ALTER SEQUENCE client_id_seq RESTART WITH 100;'
        )
    ]
