# Generated by Django 3.1.7 on 2022-03-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_auto_20220309_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(default='material', max_length=50, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.userprofile', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='offer',
            name='from_client',
            field=models.JSONField(blank=True, null=True, verbose_name='От заказчика'),
        ),
    ]
