# Generated by Django 3.1.7 on 2022-03-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_auto_20220310_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_contact', to='server.userprofile', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='offer',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.objects', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offer_author', to='server.userprofile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='server.client', verbose_name='Клиент'),
        ),
    ]
