# Generated by Django 3.1.7 on 2022-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20220310_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер карты')),
                ('due_date', models.DateField(verbose_name='Срок действия')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.cards', verbose_name='Карточка')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Карточка пользователей',
                'verbose_name_plural': 'Карточки пользователей',
                'db_table': 'cards_users',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cards',
            field=models.ManyToManyField(through='server.CardsUsers', to='server.Cards', verbose_name='Карточки'),
        ),
    ]
