# Generated by Django 3.1.7 on 2022-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20220323_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_category',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Категория прав'),
        ),
    ]
