# Generated by Django 3.1.7 on 2022-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_userprofile_auto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsusers',
            name='due_date',
            field=models.CharField(max_length=7, verbose_name='Срок действия'),
        ),
    ]
