# Generated by Django 3.1.7 on 2022-04-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0038_auto_20220323_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60, verbose_name='Название')),
                ('default_settings', models.JSONField(blank=True, null=True, verbose_name='Настройки по умолчанию')),
            ],
            options={
                'verbose_name': 'Виджет',
                'verbose_name_plural': 'Виджеты',
                'db_table': 'widgets',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Работает'),
        ),
        migrations.CreateModel(
            name='WidgetsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, null=True, verbose_name='Настройки')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.userprofile', verbose_name='Пользователь')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.widgets', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Виджет пользователя',
                'verbose_name_plural': 'Виджеты пользователей',
                'db_table': 'widgets_users',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='widgets',
            field=models.ManyToManyField(through='server.WidgetsUsers', to='server.Widgets', verbose_name='Виджеты'),
        ),
    ]
