# Generated by Django 3.1.7 on 2022-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_auto_20220406_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='max_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество'),
        ),
    ]
